# Generated by Django 6.0.4 on 2026-05-08 07:37

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models
from django.utils import timezone


def backfill_borrow_amounts(apps, schema_editor):
    Borrow = apps.get_model('borrowing', 'Borrow')
    for borrow in Borrow.objects.select_related('book'):
        borrow_fee = (borrow.book.price * Decimal('0.30')).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        if borrow.return_date:
            overdue_days = (borrow.return_date.date() - borrow.due_date).days
        else:
            overdue_days = (timezone.now().date() - borrow.due_date).days

        borrow.borrow_fee = borrow_fee
        borrow.payment_status = 'paid'
        if not borrow.payment_date:
            borrow.payment_date = borrow.borrow_date
        if overdue_days > 0:
            borrow.is_overdue = True
            if borrow.status == 'active':
                borrow.status = 'overdue'
            borrow.fine_amount = borrow_fee
            borrow.amount_due = borrow_fee * Decimal('2.00')
        else:
            borrow.fine_amount = Decimal('0.00')
            borrow.amount_due = borrow_fee
        borrow.save(update_fields=[
            'borrow_fee', 'amount_due', 'payment_status', 'payment_date',
            'is_overdue', 'status', 'fine_amount',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrow_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='borrow',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paye'), ('unpaid', 'Non paye')], default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('returned', 'Retourne'), ('overdue', 'En retard')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuve'), ('rejected', 'Rejete'), ('cancelled', 'Annule')], default='pending', max_length=20),
        ),
        migrations.RunPython(backfill_borrow_amounts, migrations.RunPython.noop),
    ]
