# Generated by Django 6.0.4 on 2026-05-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_borrow_amount_due_borrow_borrow_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paye'), ('unpaid', 'Non paye')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Paiement en attente'), ('active', 'Actif'), ('returned', 'Retourne'), ('overdue', 'En retard'), ('cancelled', 'Annule')], default='pending_payment', max_length=20),
        ),
    ]
