# Generated by Django 6.0.3 on 2026-04-19 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage %'), ('fixed', 'Montant fixe €')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usage_limit', models.IntegerField(blank=True, help_text="Nombre total d'utilisations autorisées", null=True)),
                ('times_used', models.IntegerField(default=0, editable=False)),
                ('per_user_limit', models.IntegerField(default=1, help_text='Utilisations par utilisateur')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('applicable_to_all', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_books', models.ManyToManyField(blank=True, to='catalog.book')),
                ('applicable_users', models.ManyToManyField(blank=True, related_name='available_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
                'ordering': ['-created_at'],
            },
        ),
    ]
