# Generated by Django 6.0.3 on 2026-04-17 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('cancelled', 'Annulé'), ('completed', 'Complété'), ('expired', 'Expiré')], default='active', max_length=20)),
                ('queue_position', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['queue_position', '-reservation_date'],
            },
        ),
        migrations.CreateModel(
            name='ReservationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ready_for_pickup', 'Prêt pour récupération'), ('expiring_soon', 'Expiration bientôt'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], max_length=50)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Notification de réservation',
                'verbose_name_plural': 'Notifications de réservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reservations', models.IntegerField(default=0)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_queue', to='catalog.book')),
            ],
            options={
                'verbose_name': "File d'attente de réservation",
                'verbose_name_plural': "Files d'attente de réservation",
            },
        ),
    ]
