# Generated by Django 4.2.11 on 2026-05-07 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remise appliquee aux commandes de ce compte en pourcentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
