# Generated by Django 4.2.11 on 2026-05-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_order_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='order_discount_percentage',
        ),
    ]
