# Generated by Django 6.0.4 on 2026-05-07 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_order_discount_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('order', 'Commande'), ('payment', 'Paiement'), ('borrow', 'Emprunt'), ('reservation', 'Reservation'), ('account', 'Compte'), ('other', 'Autre')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Haute')], default='normal', max_length=20)),
                ('message', models.TextField()),
                ('admin_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('in_progress', 'En cours'), ('resolved', 'Resolue'), ('closed', 'Fermee')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reclamation',
                'verbose_name_plural': 'Reclamations',
                'ordering': ['-created_at'],
            },
        ),
    ]
