# Generated by Django 6.0.4 on 2026-05-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Photo de profil', max_length=255, null=True, upload_to='accounts/avatars/'),
        ),
    ]
