# Generated by Django 6.0.4 on 2026-05-11 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reservation', 'Reservation'), ('borrow', 'Emprunt'), ('order', 'Commande'), ('payment', 'Paiement'), ('system', 'Systeme')], default='system', max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification utilisateur',
                'verbose_name_plural': 'Notifications utilisateur',
                'ordering': ['-created_at'],
            },
        ),
    ]
