# Generated by Django 6.0.4 on 2026-04-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Image de couverture du livre', null=True, upload_to='books/covers/'),
        ),
    ]
